### ISSUE TITLE
和官方的一样吗?可以加速PC吗?

### ISSUE THREAD

**Issue by jiasai007** [ttc0419/uuplugin#1]
和官方的一样吗?可以加速PC吗?
官方发布的openwrt的UU插件 不支持PC加速
请问你这个可以吗?

**Comment by ttc0419** [comment]
不可以，这个项目只是官方二进制的ipk打包版而已。

**Comment by zzzop** [comment]
我mispel不管安装哪个版本都是3.9.2，官方就没更新过

> 和官方的一样吗?可以加速PC吗? 官方发布的openwrt的UU插件 不支持PC加速 请问你这个可以吗?
