### ISSUE TITLE
openwrt Makefile 编译

### ISSUE THREAD

**Issue by sbwml** [ttc0419/uuplugin#5]
话说为什么不做成 openwrt makefile 的方式呀，这样可以方便构建固件时编译进去

**Comment by ttc0419** [comment]
因为openwrt还需要配置SDK，构建rootfs，当初就是因为这个原因才手动方式打包，而且本身就是二进制软件不需要SDK任何东西。做成ipk还可以在任何对应架构，安装SDK的话每个target还要重新配置更麻烦。
