### ISSUE TITLE
armv8架构适配

### ISSUE THREAD

**Issue by Xinhg** [ttc0419/uuplugin#9]
能否对armv8架构适配一下？我用的GL-MT3000是ARMv8 Processor rev 4架构，现在用的人也挺多的

**Comment by ttc0419** [comment]
openwrt没有armv8这个说法，把```grep '^DISTRIB_ARCH' /etc/openwrt_release```输出贴出来。

**Comment by Xinhg** [comment]
不好意思我知道了，是aarch64_cortex-a53,我一直在尝试安装arm的，所以不兼容
